"""供应商中立、可检查的 Context 规划契约。"""

from harnessix.context.compaction_runtime_contracts import CompactionRuntimeConfig
from harnessix.context.contracts import (
    ContextBuildInput,
    ContextConsistencySnapshot,
    ContextFragment,
    ContextFragmentDecision,
    ContextFragmentKind,
    ContextInspection,
    ContextInspectionRecord,
    ContextInspectionV2,
    ContextInspectionV3,
    ContextLimits,
    ContextPrepared,
    ContextSourceDocument,
    ContextSourceDocumentSnapshot,
    ContextSourceObservation,
    ContextSourceSnapshot,
    ContextTrust,
    PreparedContext,
)
from harnessix.context.engine import ContextEngine, ContextPreparationError, estimate_tokens
from harnessix.context.ports import AsyncContextPlanner, ContextPlanner
from harnessix.context.sources import (
    ContextSource,
    ContextSourceError,
    EnvironmentContextSource,
    GitContextSource,
    ProjectInstructionSource,
    SourcedContextEngine,
    WorkspaceContextSource,
)
from harnessix.context.tool_result_contracts import (
    ModelHistoryInspection,
    ModelHistoryInspectionRecord,
    ModelHistoryInspectionV2,
    ToolResultViewDecision,
    ToolResultViewPolicy,
)

__all__ = [
    "AsyncContextPlanner",
    "ContextBuildInput",
    "CompactionRuntimeConfig",
    "ContextConsistencySnapshot",
    "ContextEngine",
    "ContextFragment",
    "ContextFragmentDecision",
    "ContextFragmentKind",
    "ContextInspection",
    "ContextInspectionRecord",
    "ContextInspectionV2",
    "ContextInspectionV3",
    "ContextLimits",
    "ContextPlanner",
    "ContextPreparationError",
    "ContextPrepared",
    "ContextSource",
    "ContextSourceDocument",
    "ContextSourceDocumentSnapshot",
    "ContextSourceError",
    "ContextSourceObservation",
    "ContextSourceSnapshot",
    "ContextTrust",
    "EnvironmentContextSource",
    "GitContextSource",
    "ModelHistoryInspection",
    "ModelHistoryInspectionRecord",
    "ModelHistoryInspectionV2",
    "PreparedContext",
    "ProjectInstructionSource",
    "SourcedContextEngine",
    "ToolResultViewDecision",
    "ToolResultViewPolicy",
    "WorkspaceContextSource",
    "estimate_tokens",
]
