"""Harnessix Code公共Agent Protocol合同与投影。"""

from harnessix.protocol.codec import ProtocolDecodeError, decode_client_frame
from harnessix.protocol.compatibility import decode_known_notification
from harnessix.protocol.contracts import (
    AGENT_PROTOCOL_VERSION,
    ApprovalRespondParams,
    EventsNextParams,
    EventsNextResult,
    EventsReplayParams,
    EventsReplayResult,
    InitializeParams,
    InitializeResult,
    JsonRpcError,
    JsonRpcErrorResponse,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcSuccessResponse,
    PublicEvent,
    PublicItemDelta,
    QuestionRespondParams,
    ThreadArchiveParams,
    ThreadCreateParams,
    ThreadForkParams,
    ThreadGetParams,
    ThreadListParams,
    ThreadResumeParams,
    ThreadView,
    TurnCancelParams,
    TurnResumeParams,
    TurnRetryParams,
    TurnStartParams,
    TurnSteerParams,
    TurnView,
    validate_server_output,
)
from harnessix.protocol.projection import (
    project_event,
    project_replay,
    project_thread,
    project_turn,
)
from harnessix.protocol.requests import (
    ProtocolRequestClaim,
    ProtocolRequestError,
    ProtocolRequestRecord,
    SQLiteProtocolRequestStore,
    request_fingerprint,
)

__all__ = [
    "AGENT_PROTOCOL_VERSION",
    "ApprovalRespondParams",
    "EventsNextParams",
    "EventsNextResult",
    "EventsReplayParams",
    "EventsReplayResult",
    "InitializeParams",
    "InitializeResult",
    "JsonRpcError",
    "JsonRpcErrorResponse",
    "JsonRpcNotification",
    "JsonRpcRequest",
    "JsonRpcSuccessResponse",
    "PublicEvent",
    "PublicItemDelta",
    "ProtocolDecodeError",
    "ProtocolRequestClaim",
    "ProtocolRequestError",
    "ProtocolRequestRecord",
    "SQLiteProtocolRequestStore",
    "QuestionRespondParams",
    "ThreadArchiveParams",
    "ThreadCreateParams",
    "ThreadForkParams",
    "ThreadGetParams",
    "ThreadListParams",
    "ThreadResumeParams",
    "ThreadView",
    "TurnCancelParams",
    "TurnResumeParams",
    "TurnRetryParams",
    "TurnStartParams",
    "TurnSteerParams",
    "TurnView",
    "decode_known_notification",
    "decode_client_frame",
    "project_event",
    "project_replay",
    "project_thread",
    "project_turn",
    "request_fingerprint",
    "validate_server_output",
]
